const utils = require('../utils');

const changelogHeader = `
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html).

Generated by [\`auto-changelog\`](https://github.com/CookPete/auto-changelog).
`;

describe('sanitizeChangelog', () => {
  it('replace invalid `Updated` keyword', () => {
    const changelogContent = `
        ${changelogHeader}
        ## [0.2.4] - 2019-05-27
        ### Updated
        - Replace source directory for antd imports
        ## [0.2.3] - 2019-02-15
        ### Removed
        - Some unused code

        ### Fixed
        - Sharing props when using wrapWithField HOC
        - Build-storybook script
        `;

    expect(utils.sanitizeChangelog(changelogContent)).not.toContain('### Updated');
    expect(utils.sanitizeChangelog(changelogContent)).toContain('### Changed');
  });

  it('replace misspelled title keywords with Changed', () => {
    const changelogContent = `
    ${changelogHeader}
    ## [0.2.4] - 2019-05-27
    ### Changad
    - Replace source directory for antd imports
    ## [0.2.3] - 2019-02-15
    ### Remved
    - Some unused code
    ### Addedddd
    - Changelog
    `;

    expect(utils.sanitizeChangelog(changelogContent)).not.toContain('### Changad');
    expect(utils.sanitizeChangelog(changelogContent)).toContain('### Changed');
    expect(utils.sanitizeChangelog(changelogContent)).not.toContain('### Remved');
    expect(utils.sanitizeChangelog(changelogContent)).toContain('### Changed');
    expect(utils.sanitizeChangelog(changelogContent)).not.toContain('### Addedddd');
    expect(utils.sanitizeChangelog(changelogContent)).toContain('### Changed');
  });

  it('fix keyword if there is only bad casing', () => {
    const changelogContent = `
    ${changelogHeader}
    ## [0.2.4] - 2019-05-27
    ### changed
    - Replace source directory for antd imports
    ## [0.2.3] - 2019-02-15
    ### fixed
    - Sharing props when using wrapWithField HOC
    `;

    expect(utils.sanitizeChangelog(changelogContent)).not.toContain('### changed');
    expect(utils.sanitizeChangelog(changelogContent)).toContain('### Changed');
    expect(utils.sanitizeChangelog(changelogContent)).not.toContain('### fixed');
    expect(utils.sanitizeChangelog(changelogContent)).toContain('### Fixed');
  });
});
